# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        default: true
      pgo:
        type: boolean
        default: false

jobs:
  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "latest"

    - name: Clone 🧬
      uses: actions/checkout@v4
      with:
        submodules: "true"

    - name: Configure sccache
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Setup Rust (shared)
      run: ./.github/workflows/scripts/setup-rust.sh linux ${{ matrix.arch }}

    - name: Allocate swap
      run: ./.github/workflows/scripts/allocate-swap.sh ${{ matrix.arch }}

    - name: Setup noraneko (shared)
      run: ./.github/workflows/scripts/setup-noraneko.sh linux ${{ matrix.arch }} ${{ inputs.debug }} ${{ inputs.pgo }}

    - name: Build & Package (shared)
      run: ./.github/workflows/scripts/build-and-package.sh linux ${{ matrix.arch }} ${{ inputs.pgo }}

    # Publish START
    - name: Publish Package Mozilla Artifact 🎁
      uses: actions/upload-artifact@v4
      with:
        name: noraneko-linux-${{ matrix.arch }}-moz-artifact
        path: ./noraneko-linux-amd64-moz-artifact.tar.xz

    - name: Publish dist/host for MAR
      uses: actions/upload-artifact@v4
      with:
        name: linux-amd64-dist-host
        path: obj-x86_64-pc-linux-gnu/dist/host/
        overwrite: true

    - name: Publish nora-application.ini for MAR
      uses: actions/upload-artifact@v4
      with:
        name: linux-amd64-application-ini
        path: ./nora-application.ini
        overwrite: true
    # Publish END
