# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

#! SELF HOST DOES NOT SUPPORTED
#TODO: separate Publish to other workflow

on:
  workflow_call:
    inputs:
      x86_64_artifact_name:
        type: string
        default: ""
      aarch64_artifact_name:
        type: string
        default: ""
      beta:
        type: boolean
        default: false
      MOZ_BUILD_DATE:
        type: string
        default: ""

jobs:
  Integration:
    runs-on: macos-latest
    steps:
        - name: Clone 📥
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'

        - name: download AArch64 build artifact 📥
          uses: actions/download-artifact@v4
          with:
            name: ${{ inputs.aarch64_artifact_name }}
            path: ./

        - name: download x86_64 build artifact 📥
          uses: actions/download-artifact@v4
          with:
            name: ${{ inputs.x86_64_artifact_name }}
            path: ./

        - name: Extract 📦
          run: |
            brew install gnu-tar
            export PATH=/usr/local/opt/gnu-tar/libexec/gnubin:$PATH
            tar -xf ./noraneko-x86_64-apple-darwin-with-pgo.tar.gz
            tar -xf ./noraneko-aarch64-apple-darwin-with-pgo.tar.gz

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Check Branding Type
          shell: bash
          run: |
            if [[ $GHA_BETA == 'true' ]]; then
              export APP_NAME=`echo "Noraneko Beta"`
              echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
            else
              export APP_NAME=`echo "Noraneko"`
              echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
            fi
          env:
            GHA_BETA: ${{ inputs.beta }}

        - name: Create environment 🌲
          shell: bash
          run: |
            ./mach --no-interactive bootstrap --application-choice browser
            echo -e "ac_add_options --enable-bootstrap" >> mozconfig
            ./mach configure

        - name: Install apple-codesign 🍎
          run: |
            cargo install apple-codesign

        - name: Extract .app from dmg 📦
          run: |
            rm -rf "./obj-x86_64-apple-darwin/dist/noraneko/*.app"
            rm -rf "./obj-aarch64-apple-darwin/dist/noraneko/*.app"

            hdiutil attach ./obj-x86_64-apple-darwin/dist/noraneko*.mac.dmg
            cp -r "/Volumes/Noraneko/${{ env.APP_NAME }}.app" ./obj-x86_64-apple-darwin/dist/noraneko/

            hdiutil detach /Volumes/Noraneko/

            hdiutil attach ./obj-aarch64-apple-darwin/dist/noraneko*.mac.dmg
            cp -r "/Volumes/Noraneko/${{ env.APP_NAME }}.app" ./obj-aarch64-apple-darwin/dist/noraneko/

            hdiutil detach /Volumes/Noraneko/

        - name: Integration 🗃
          run: |
            ./mach python "./toolkit/mozapps/installer/unify.py" "./obj-x86_64-apple-darwin/dist/noraneko/${{ env.APP_NAME }}.app" "./obj-aarch64-apple-darwin/dist/noraneko/${{ env.APP_NAME }}.app"

        - name: Create DMG 📦
          run: |
            ./mach python -m mozbuild.action.make_dmg ./obj-x86_64-apple-darwin/dist/noraneko noraneko-macOS-universal-moz-artifact.dmg

            cp ./obj-x86_64-apple-darwin/dist/noraneko*update_framework_artifacts.zip ./noraneko-macOS.update_framework_artifacts.zip
            cp ./obj-x86_64-apple-darwin/dist/noraneko/Noraneko.app/Contents/Resources/application.ini ./nora-application.ini

        # Publish Start
        - name: Remove old uploaded artifacts
          uses: geekyeggo/delete-artifact@v5.1.0
          with:
            name: |
              noraneko-mac-x86_64-package
              noraneko-mac-aarch64-package

        - name: Publish Package Mozilla Artifact for dev 🎁
          uses: actions/upload-artifact@v4
          with:
            name: noraneko-mac-universal-moz-artifact-dev
            if-no-files-found: ignore
            path: |
              ./noraneko-macOS-universal-moz-artifact.dmg

        - name: Publish Package Mozilla Artifact for release 🎁
          uses: actions/upload-artifact@v4
          with:
            name: noraneko-mac-universal-moz-artifact-release
            if-no-files-found: ignore
            path: |
              ./noraneko-macOS-universal-moz-artifact.dmg
              ./noraneko-macOS.update_framework_artifacts.zip

        - name: Publish dist/host for MAR
          uses: actions/upload-artifact@v4
          with:
            name: macOS-universal-dist-host
            path: obj-x86_64-apple-darwin/dist/host/
            overwrite: true

        - name: Publish nora-application.ini for MAR
          uses: actions/upload-artifact@v4
          with:
            name: macOS-universal-application-ini
            path: ./nora-application.ini
            overwrite: true
        # Publish End
