# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

on:
    workflow_call:
      inputs:
        browser-artifact-name:
          description: 'Artifact to download'
          required: true
          default: 'noraneko-win-amd64-profile-generate-mode-package'
          type: string

jobs:
  generate-profdata-and-jarlog:
    name: Generate PGO Profile Data and Jarlog (Windows)
    runs-on: windows-latest
    steps:
      # Download the build artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.browser-artifact-name }}
          path: C:\artifact

      # Checkout source
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install MozillaBuild
      - name: Install MozillaBuild
        run: |
          (New-Object System.Net.WebClient).DownloadFile("https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe", "C:\MozillaBuildSetup-Latest.exe")
          C:\MozillaBuildSetup-Latest.exe /S | Out-Null

      # Generate profdata and jarlog
      - name: Generate Profdata and Jarlog
        run: |
          $Env:USE_MINTTY = "0"
          $workspace_dir = [regex]::replace($env:GITHUB_WORKSPACE, "^([A-Z]):", { "/" + $args.value.Substring(0, 1).toLower() }) -replace "\\","/"
          echo "cd $workspace_dir" '' >> mozilla-build-run.sh
          echo 'export PATH=/c/mozilla-build/msys2/usr/bin:$PATH' '' >> mozilla-build-run.sh
          echo './mach --no-interactive bootstrap --application-choice browser' '' >> mozilla-build-run.sh
          echo 'LLVM_PROFDATA=/c/Users/runneradmin/.mozbuild/clang/bin/llvm-profdata.exe JARLOG_FILE=en-US.log ./mach python build/pgo/profileserver.py --binary /c/artifact/noraneko/noraneko.exe' '' >> mozilla-build-run.sh
          C:\mozilla-build\start-shell.bat $workspace_dir\mozilla-build-run.sh

      # Publish results
      - name: Upload Profdata and Jarlog
        uses: actions/upload-artifact@v4
        with:
          name: noraneko-win-amd64-profile-generate-output
          path: |
            merged.profdata
            en-US.log
