# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# © 2023 Floorp Projects & Contributors

name: "(A) ⚒ Mac build"

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: true
      package-full:
        type: boolean
        required: true

run-name: Mac build
jobs:
  get-buildid:
    runs-on: ubuntu-latest
    outputs:
      buildids: ${{ steps.get.outputs.bid }}
    steps:
      - id: get
        shell: bash -xe {0}
        run: |
          bdat=`date +"%Y%m%d%I%M%S"`
          echo "bid=${bdat}" >> $GITHUB_OUTPUT

  run-build:
    needs: [get-buildid]
    uses: ./.github/workflows/mac_build.yml
    with:
      debug: ${{inputs.debug}}
      MOZ_BUILD_DATE: ${{needs.get-buildid.outputs.buildids}}

  run-package:
    needs: [get-buildid, run-build]
    uses: ./.github/workflows/mac_integration.yml
    secrets: inherit
    with:
      x86_64_artifact_name: noraneko-mac-x86_64-dev
      aarch64_artifact_name: noraneko-mac-aarch64-dev
      MOZ_BUILD_DATE: ${{needs.get-buildid.outputs.buildids}}
