# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: "(A) ⚒ Windows build"

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: true
      pgo:
        type: boolean
        default: false
        required: true

  workflow_call:
    inputs:
      debug:
        type: boolean
        required: true
      pgo:
        type: boolean
        default: false
        required: true

run-name: ${{toJSON(inputs.pgo) == 'true' && '[PGO] ' || ''}}Windows x64 build${{toJSON(inputs.debug) == 'true' && ' Debug' || ''}}
jobs:
  part-1:
    name: Windows x64 build${{toJSON(inputs.debug) == 'true' && ' Debug' || ''}}
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      debug: ${{inputs.debug}}
      profile-generate-mode: ${{inputs.pgo}}

  part-2:
    name: Windows x64 Generate Profile for Guided Optimazation
    if: inputs.pgo
    needs: part-1
    uses: ./.github/workflows/windows_pgo.yml
    secrets: inherit
    with:
      browser-artifact-name: noraneko-win-amd64-profile-generate-mode-package

  part-3:
    name: Windows x64 build${{toJSON(inputs.debug) == 'true' && ' Debug' || ''}}
    if: inputs.pgo
    needs: part-2
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      debug: ${{inputs.debug}}
      pgo_artifact_name: noraneko-win-amd64-profile-generate-output
